

[package]
name = "hyper-simple-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_simple_server"
path = "./lib.rs"

[[bin]]
name = "example"
path = "./example.rs"


[features]
default = []


[dependencies]

futures = { version = "*", default-features = true }
hyper = { version = "*", default-features = true, features = ["full"] }
http-body = { version = "*", default-features = true }
tokio = { version = "*", default-features = true, features = ["full"] }

tokio-rustls = { version = "*", default-features = true }
rustls = { version = "*", default-features = true }

tokio-native-tls = { version = "*", default-features = true }
native-tls = { version = "*", default-features = true }

rustls-pemfile = { version = "*", default-features = true }

