

[package]
name = "hyper-simple-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_simple_server"
path = "./lib.rs"

[[bin]]
name = "example"
path = "./example.rs"


[features]
default = []


[dependencies]

hyper = { version = "*", default-features = false, features = ["http1", "http2", "server"] }
tokio = { version = "*", default-features = false, features = ["rt", "rt-multi-thread", "net"] }
http-body = { version = "*", default-features = false, features = [] }

rustls = { version = "*", default-features = false, features = [] }
tokio-rustls = { version = "*", default-features = false, features = [] }
rustls-pemfile = { version = "*", default-features = false, features = [] }

native-tls = { version = "*", default-features = false, features = ["alpn"] }
tokio-native-tls = { version = "*", default-features = false, features = [] }

futures = { version = "*", default-features = false, features = [] }
path-tree = { version = "*", default-features = false, features = [] }

