

[package]
name = "hyper-simple-server"
version = "0.0.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
edition = "2018"
license = "MIT"
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "hyper_simple_server"
path = "./lib.rs"

[[bin]]
name = "example"
path = "./example.rs"
required-features = [
	"hss-main",
	"hss-server-http",
	"hss-routes",
	"hss-http",
	"hss-extensions",
	"hss-exports",
]




[features]

default = ["hss-full"]

hss-full = [
	"hss-full-http1",
	"hss-full-http2",
]

hss-full-http1 = [
	"hss-full-common",
	"hss-server-http1",
]

hss-full-http2 = [
	"hss-full-common",
	"hss-server-http2",
]

hss-full-common = [
	"hss-server-mt",
	"hss-handler",
	"hss-routes",
	"hss-config",
	"hss-accepter",
	"hss-tls-rust",
	"hss-tls-native",
	"hss-http",
	"hss-exports",
	"hss-extensions",
	"hss-main",
]

hss-server-full = [
	"hss-server-mt",
	"hss-server-http1",
	"hss-server-http2",
]

hss-server-mt = [
	"hss-server",
	"tokio--rt-multi-thread",
]

hss-server-http1 = [
	"hss-server",
	"hss-server-http",
	"hyper--http1",
]

hss-server-http2 = [
	"hss-server",
	"hss-server-http",
	"hyper--http2",
]

hss-server-http = []

hss-server = [
	"hss-config",
	"hss-accepter",
	"hyper--server",
#	"hyper--runtime", # NOTE:  Optional for timeouts support.
	"http",
	"http-body",
	"bytes",
	"tokio--rt",
#	"hss-jemalloc",
#	"hss-server-debug-strace",
#	"hss-server-debug-jemalloc",
]

hss-accepter = [
	"hss-config",
	"tokio--net",
	"futures",
]

hss-config = []

hss-handler = [
	"hyper",
	"http",
	"http-body",
	"bytes",
	"futures",
]

hss-routes = [
	"hss-handler",
	"path-tree",
]

hss-tls-rust = [
	"hss-tls-any",
	"rustls",
	"rustls-pemfile",
	"tokio-rustls",
]

hss-tls-native = [
	"hss-tls-any",
	"native-tls",
	"native-tls/alpn",
	"tokio-native-tls",
]

hss-tls-any = []

hss-http = [
	"http",
	"http-body",
	"bytes",
	"hyper",
]

hss-extensions = []

hss-exports = []

hss-main = []

hss-jemalloc = [
	"jemallocator",
]

hss-server-debug-strace = []

hss-server-debug-jemalloc = [
	"jemalloc-sys/stats",
]


hyper--server = ["hyper", "hyper/server"]
hyper--http1 = ["hyper", "hyper/http1", "hyper--http"]
hyper--http2 = ["hyper", "hyper/http2", "hyper--http"]
hyper--http = ["hyper", "hyper/http2"]
hyper--runtime = ["hyper", "hyper/runtime"]
tokio--rt = ["tokio", "tokio/rt"]
tokio--rt-multi-thread = ["tokio", "tokio/rt-multi-thread"]
tokio--net = ["tokio", "tokio/net"]


features-fuzzing = []




[dependencies]

hyper = { version = "*", default-features = false, features = [], optional = true }
tokio = { version = "*", default-features = false, features = [], optional = true }
http = { version = "*", default-features = false, features = [], optional = true }
http-body = { version = "*", default-features = false, features = [], optional = true }
bytes = { version = "*", default-features = false, features = [], optional = true }

rustls = { version = "*", default-features = false, features = [], optional = true }
tokio-rustls = { version = "*", default-features = false, features = [], optional = true }
rustls-pemfile = { version = "*", default-features = false, features = [], optional = true }

native-tls = { version = "*", default-features = false, features = [], optional = true }
tokio-native-tls = { version = "*", default-features = false, features = [], optional = true }

futures = { version = "*", default-features = false, features = [], optional = true }
path-tree = { version = "*", default-features = false, features = [], optional = true }

jemallocator = { version = "*", default-features = false, features = [], optional = true }
jemalloc-sys = { version = "*", default-features = false, features = [], optional = true }

